### PR TITLE
Please, Review the Feature 3 code.

### PR DESCRIPTION
**Pull request by AbbosB12**

### CODE REVIEW

**Review by Marat311 — APPROVED** [review]
👏

**Review by blishchenko1981 — APPROVED** [review]

**Review by KseniiaMazanko — CHANGES_REQUESTED** [review]
Abbos I don't understand what you did in your "Then" step definition. It says that you need to find the most popular book genre. Can you explain how line 18-20 find that most popular book genre? Maybe I just don't get it?

**Comment by blishchenko1981** [comment]
Kseniia , are you paying back to Abbos because he told you didn't name your branch After yourself???)))))

**Comment by KseniiaMazanko** [comment]
Lmao 🤣  no, just trying to figure it out. This user story is very confusing to me, I think the steps were incorrectly given to us

**Comment by Marat311** [comment]
Yes I also saw this assertion, but I thought maybe after merging I will see what will be the result

**Comment by KseniiaMazanko** [comment]
I texted Asya for additional explanation of that user story, I'll share with you guys when she answers. According to the steps that she provided I don't see the way to find the most popular genre 🤔

**Review by KseniiaMazanko — APPROVED** [review]
👍

**Review by KseniiaMazanko — APPROVED** [review]
Great!

**Review by blishchenko1981 — APPROVED** [review]

**Pull request merged**
